# Generated by Django 4.2.7 on 2023-11-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nomeF',
            new_name='nome',
        ),
    ]
